### ISSUE TITLE
Bias current conversion from coarse/fine values

### ISSUE THREAD

**Issue by jo-m** [inivation/libcaer#40]
Hi

In the jAER bias config panel, an estimated physical current/voltate is shown when setting coarse and fine values (I think those estimates are calculated [here](https://github.com/SensorsINI/jaer/blob/60f9b4e7985993d4403479ea75abc3404e61c0b9/src/net/sf/jaer/biasgen/Masterbias.java)). Is there any way in libcaer to

1. estimate a current from a coarse/fine value set, and
2. get the best matching coarse/fine value set for a given current?

**Comment by llongi** [comment]
Currently this does not exist, but it is in our long-term plans to provide such conversion for Dynapse and DAVIS.

**Comment by llongi** [comment]
Added in commit e654c20f5f08619705b231aee42db6387ed57e17.
