### ISSUE TITLE
non monotonic timestamp alert

### ISSUE THREAD

**Issue by ardayigit** [inivation/libcaer#69]
Hello, 

When I use libcaer libraries to acquire events from an eDVS, I sometimes have the following alert: 

`2018-07-12 18:22:28 (TZ+0200): ALERT: eDVS4337 ID-1: Timestamps: non monotonic timestamp detected`

It occurs in general after launching my script multiple times without unplugging the device between two executions. I don't understand what is the meaning of this alert and what should I do to avoid it. 

Thank you in advance for your help! 
Arda

**Comment by llongi** [comment]
Hello, do you get the alert while the eDVS is running, or right after startup?
It basically means that for some reason the timestamp went backwards for an event and it got thus discarded, this can have two reasons mainly:
1) there is some left over data in some device/OS buffers from the last run, so it sees a "high" timestamp when it starts up and then the normal "low" ones again starting from zero
2) some data is lost/corrupted in transit via USB, and two timestamps happen to not be in the right order
If you really only see this rarely right after you start your program, it's almost certainly case 1 and nothing to worry about.
We do try to flush out all device-side buffers at startup, but there might be cases where some old data survives, as we don't wait indefinitely to avoid long startup times.
